name: OpenFAAS
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1        
    - name: OpenFAAS
      run: |
        echo $DOCKER_PASSWORD | docker login --username xena --password-stdin
      
        wget -O faas https://github.com/openfaas/faas-cli/releases/download/0.9.2/faas-cli
        chmod +x faas
        echo $FAAS_PASSWORD | ./faas login -g https://gw.within.website --username admin --password-stdin
        ./faas build -f toki-pona-parser.yml
        ./faas push -f toki-pona-parser.yml
        ./faas deploy -f toki-pona-parser.yml
        
        ./faas build -f toki-pona-verb-parser.yml
        ./faas push -f toki-pona-verb-parser.yml
        ./faas deploy -f toki-pona-verb-parser.yml
      env:
        DOCKER_USERNAME: "xena"
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        FAAS_VERSION: "0.9.2"
        FAAS_PASSWORD: "${{ secrets.FAAS_PASSWORD }}"
